version: '3'
services: 
  frontend:
    restart: always
    build: ./frontend 
    ports: 
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOCKIDAR_USEPOLLING=true
  api:
    restart: always
    build: ./api
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: very-strong-db-password
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: very-strong-db-password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: adminpass
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongodb_data: 